/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrumsRouteImport } from './routes/drums'
import { Route as GuitarRouteImport } from './routes/guitar'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PianoRouteImport } from './routes/piano'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as UkuleleRouteImport } from './routes/ukulele'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as TunersGuitarRouteImport } from './routes/tuners.guitar'
import { Route as TunersUkuleleRouteImport } from './routes/tuners.ukulele'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrumsRoute = DrumsRouteImport.update({
  id: '/drums',
  path: '/drums',
  getParentRoute: () => rootRouteImport,
} as any)
const GuitarRoute = GuitarRouteImport.update({
  id: '/guitar',
  path: '/guitar',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoRoute = PianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const UkuleleRoute = UkuleleRouteImport.update({
  id: '/ukulele',
  path: '/ukulele',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const TunersGuitarRoute = TunersGuitarRouteImport.update({
  id: '/tuners/guitar',
  path: '/tuners/guitar',
  getParentRoute: () => rootRouteImport,
} as any)
const TunersUkuleleRoute = TunersUkuleleRouteImport.update({
  id: '/tuners/ukulele',
  path: '/tuners/ukulele',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drums': typeof DrumsRoute
  '/guitar': typeof GuitarRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/piano': typeof PianoRoute
  '/recordings': typeof RecordingsRoute
  '/ukulele': typeof UkuleleRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/tuners/guitar': typeof TunersGuitarRoute
  '/tuners/ukulele': typeof TunersUkuleleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drums': typeof DrumsRoute
  '/guitar': typeof GuitarRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/piano': typeof PianoRoute
  '/recordings': typeof RecordingsRoute
  '/ukulele': typeof UkuleleRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/tuners/guitar': typeof TunersGuitarRoute
  '/tuners/ukulele': typeof TunersUkuleleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drums': typeof DrumsRoute
  '/guitar': typeof GuitarRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/piano': typeof PianoRoute
  '/recordings': typeof RecordingsRoute
  '/ukulele': typeof UkuleleRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/tuners/guitar': typeof TunersGuitarRoute
  '/tuners/ukulele': typeof TunersUkuleleRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drums'
    | '/guitar'
    | '/login'
    | '/mcp'
    | '/piano'
    | '/recordings'
    | '/ukulele'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/tuners/guitar'
    | '/tuners/ukulele'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drums'
    | '/guitar'
    | '/login'
    | '/mcp'
    | '/piano'
    | '/recordings'
    | '/ukulele'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/tuners/guitar'
    | '/tuners/ukulele'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/drums'
    | '/guitar'
    | '/login'
    | '/mcp'
    | '/piano'
    | '/recordings'
    | '/ukulele'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/tuners/guitar'
    | '/tuners/ukulele'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrumsRoute: typeof DrumsRoute
  GuitarRoute: typeof GuitarRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PianoRoute: typeof PianoRoute
  RecordingsRoute: typeof RecordingsRoute
  UkuleleRoute: typeof UkuleleRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  TunersGuitarRoute: typeof TunersGuitarRoute
  TunersUkuleleRoute: typeof TunersUkuleleRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drums': {
      id: '/drums'
      path: '/drums'
      fullPath: '/drums'
      preLoaderRoute: typeof DrumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guitar': {
      id: '/guitar'
      path: '/guitar'
      fullPath: '/guitar'
      preLoaderRoute: typeof GuitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano': {
      id: '/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof PianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukulele': {
      id: '/ukulele'
      path: '/ukulele'
      fullPath: '/ukulele'
      preLoaderRoute: typeof UkuleleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/guitar': {
      id: '/tuners/guitar'
      path: '/tuners/guitar'
      fullPath: '/tuners/guitar'
      preLoaderRoute: typeof TunersGuitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/ukulele': {
      id: '/tuners/ukulele'
      path: '/tuners/ukulele'
      fullPath: '/tuners/ukulele'
      preLoaderRoute: typeof TunersUkuleleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrumsRoute: DrumsRoute,
  GuitarRoute: GuitarRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PianoRoute: PianoRoute,
  RecordingsRoute: RecordingsRoute,
  UkuleleRoute: UkuleleRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  TunersGuitarRoute: TunersGuitarRoute,
  TunersUkuleleRoute: TunersUkuleleRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
