/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentLoginRouteImport } from './routes/agent-login'
import { Route as ChordsRouteImport } from './routes/chords'
import { Route as GroovesRouteImport } from './routes/grooves'
import { Route as GuitarRouteImport } from './routes/guitar'
import { Route as JamRouteImport } from './routes/jam'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PianoRouteImport } from './routes/piano'
import { Route as RecordingsRouteImport } from './routes/recordings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UkuleleRouteImport } from './routes/ukulele'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminSongsRouteImport } from './routes/admin.songs'
import { Route as ApiPreferencesRouteImport } from './routes/api/preferences'
import { Route as DrumsIndexRouteImport } from './routes/drums.index'
import { Route as DrumsTunerRouteImport } from './routes/drums.tuner'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeChallengesRouteImport } from './routes/practice.challenges'
import { Route as PracticeEarRouteImport } from './routes/practice.ear'
import { Route as PracticeProgressRouteImport } from './routes/practice.progress'
import { Route as SongsIndexRouteImport } from './routes/songs.index'
import { Route as SongsSongIdRouteImport } from './routes/songs.$songId'
import { Route as TunersDrumsRouteImport } from './routes/tuners.drums'
import { Route as TunersGuitarRouteImport } from './routes/tuners.guitar'
import { Route as TunersUkuleleRouteImport } from './routes/tuners.ukulele'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as PracticeDrumsLearnRouteImport } from './routes/practice.drums.learn'
import { Route as PracticePianoLearnRouteImport } from './routes/practice.piano.learn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentLoginRoute = AgentLoginRouteImport.update({
  id: '/agent-login',
  path: '/agent-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChordsRoute = ChordsRouteImport.update({
  id: '/chords',
  path: '/chords',
  getParentRoute: () => rootRouteImport,
} as any)
const GroovesRoute = GroovesRouteImport.update({
  id: '/grooves',
  path: '/grooves',
  getParentRoute: () => rootRouteImport,
} as any)
const GuitarRoute = GuitarRouteImport.update({
  id: '/guitar',
  path: '/guitar',
  getParentRoute: () => rootRouteImport,
} as any)
const JamRoute = JamRouteImport.update({
  id: '/jam',
  path: '/jam',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoRoute = PianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsRoute = RecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UkuleleRoute = UkuleleRouteImport.update({
  id: '/ukulele',
  path: '/ukulele',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminSongsRoute = AdminSongsRouteImport.update({
  id: '/admin/songs',
  path: '/admin/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPreferencesRoute = ApiPreferencesRouteImport.update({
  id: '/api/preferences',
  path: '/api/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const DrumsIndexRoute = DrumsIndexRouteImport.update({
  id: '/drums/',
  path: '/drums/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrumsTunerRoute = DrumsTunerRouteImport.update({
  id: '/drums/tuner',
  path: '/drums/tuner',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeChallengesRoute = PracticeChallengesRouteImport.update({
  id: '/practice/challenges',
  path: '/practice/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeEarRoute = PracticeEarRouteImport.update({
  id: '/practice/ear',
  path: '/practice/ear',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeProgressRoute = PracticeProgressRouteImport.update({
  id: '/practice/progress',
  path: '/practice/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsIndexRoute = SongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)
const TunersDrumsRoute = TunersDrumsRouteImport.update({
  id: '/tuners/drums',
  path: '/tuners/drums',
  getParentRoute: () => rootRouteImport,
} as any)
const TunersGuitarRoute = TunersGuitarRouteImport.update({
  id: '/tuners/guitar',
  path: '/tuners/guitar',
  getParentRoute: () => rootRouteImport,
} as any)
const TunersUkuleleRoute = TunersUkuleleRouteImport.update({
  id: '/tuners/ukulele',
  path: '/tuners/ukulele',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeDrumsLearnRoute = PracticeDrumsLearnRouteImport.update({
  id: '/practice/drums/learn',
  path: '/practice/drums/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticePianoLearnRoute = PracticePianoLearnRouteImport.update({
  id: '/practice/piano/learn',
  path: '/practice/piano/learn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-login': typeof AgentLoginRoute
  '/chords': typeof ChordsRoute
  '/grooves': typeof GroovesRoute
  '/guitar': typeof GuitarRoute
  '/jam': typeof JamRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/piano': typeof PianoRoute
  '/recordings': typeof RecordingsRoute
  '/signup': typeof SignupRoute
  '/ukulele': typeof UkuleleRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/songs': typeof AdminSongsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/drums/tuner': typeof DrumsTunerRoute
  '/practice/challenges': typeof PracticeChallengesRoute
  '/practice/ear': typeof PracticeEarRoute
  '/practice/progress': typeof PracticeProgressRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/tuners/drums': typeof TunersDrumsRoute
  '/tuners/guitar': typeof TunersGuitarRoute
  '/tuners/ukulele': typeof TunersUkuleleRoute
  '/drums/': typeof DrumsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/practice/drums/learn': typeof PracticeDrumsLearnRoute
  '/practice/piano/learn': typeof PracticePianoLearnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-login': typeof AgentLoginRoute
  '/chords': typeof ChordsRoute
  '/grooves': typeof GroovesRoute
  '/guitar': typeof GuitarRoute
  '/jam': typeof JamRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/piano': typeof PianoRoute
  '/recordings': typeof RecordingsRoute
  '/signup': typeof SignupRoute
  '/ukulele': typeof UkuleleRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/songs': typeof AdminSongsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/drums/tuner': typeof DrumsTunerRoute
  '/practice/challenges': typeof PracticeChallengesRoute
  '/practice/ear': typeof PracticeEarRoute
  '/practice/progress': typeof PracticeProgressRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/tuners/drums': typeof TunersDrumsRoute
  '/tuners/guitar': typeof TunersGuitarRoute
  '/tuners/ukulele': typeof TunersUkuleleRoute
  '/drums': typeof DrumsIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/songs': typeof SongsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/practice/drums/learn': typeof PracticeDrumsLearnRoute
  '/practice/piano/learn': typeof PracticePianoLearnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-login': typeof AgentLoginRoute
  '/chords': typeof ChordsRoute
  '/grooves': typeof GroovesRoute
  '/guitar': typeof GuitarRoute
  '/jam': typeof JamRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/piano': typeof PianoRoute
  '/recordings': typeof RecordingsRoute
  '/signup': typeof SignupRoute
  '/ukulele': typeof UkuleleRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/songs': typeof AdminSongsRoute
  '/api/preferences': typeof ApiPreferencesRoute
  '/drums/tuner': typeof DrumsTunerRoute
  '/practice/challenges': typeof PracticeChallengesRoute
  '/practice/ear': typeof PracticeEarRoute
  '/practice/progress': typeof PracticeProgressRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/tuners/drums': typeof TunersDrumsRoute
  '/tuners/guitar': typeof TunersGuitarRoute
  '/tuners/ukulele': typeof TunersUkuleleRoute
  '/drums/': typeof DrumsIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/songs/': typeof SongsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/practice/drums/learn': typeof PracticeDrumsLearnRoute
  '/practice/piano/learn': typeof PracticePianoLearnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-login'
    | '/chords'
    | '/grooves'
    | '/guitar'
    | '/jam'
    | '/login'
    | '/mcp'
    | '/piano'
    | '/recordings'
    | '/signup'
    | '/ukulele'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/songs'
    | '/api/preferences'
    | '/drums/tuner'
    | '/practice/challenges'
    | '/practice/ear'
    | '/practice/progress'
    | '/songs/$songId'
    | '/tuners/drums'
    | '/tuners/guitar'
    | '/tuners/ukulele'
    | '/drums/'
    | '/practice/'
    | '/songs/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/practice/drums/learn'
    | '/practice/piano/learn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-login'
    | '/chords'
    | '/grooves'
    | '/guitar'
    | '/jam'
    | '/login'
    | '/mcp'
    | '/piano'
    | '/recordings'
    | '/signup'
    | '/ukulele'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/songs'
    | '/api/preferences'
    | '/drums/tuner'
    | '/practice/challenges'
    | '/practice/ear'
    | '/practice/progress'
    | '/songs/$songId'
    | '/tuners/drums'
    | '/tuners/guitar'
    | '/tuners/ukulele'
    | '/drums'
    | '/practice'
    | '/songs'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/practice/drums/learn'
    | '/practice/piano/learn'
  id:
    | '__root__'
    | '/'
    | '/agent-login'
    | '/chords'
    | '/grooves'
    | '/guitar'
    | '/jam'
    | '/login'
    | '/mcp'
    | '/piano'
    | '/recordings'
    | '/signup'
    | '/ukulele'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/songs'
    | '/api/preferences'
    | '/drums/tuner'
    | '/practice/challenges'
    | '/practice/ear'
    | '/practice/progress'
    | '/songs/$songId'
    | '/tuners/drums'
    | '/tuners/guitar'
    | '/tuners/ukulele'
    | '/drums/'
    | '/practice/'
    | '/songs/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/signup'
    | '/practice/drums/learn'
    | '/practice/piano/learn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentLoginRoute: typeof AgentLoginRoute
  ChordsRoute: typeof ChordsRoute
  GroovesRoute: typeof GroovesRoute
  GuitarRoute: typeof GuitarRoute
  JamRoute: typeof JamRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PianoRoute: typeof PianoRoute
  RecordingsRoute: typeof RecordingsRoute
  SignupRoute: typeof SignupRoute
  UkuleleRoute: typeof UkuleleRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminSongsRoute: typeof AdminSongsRoute
  ApiPreferencesRoute: typeof ApiPreferencesRoute
  DrumsTunerRoute: typeof DrumsTunerRoute
  PracticeChallengesRoute: typeof PracticeChallengesRoute
  PracticeEarRoute: typeof PracticeEarRoute
  PracticeProgressRoute: typeof PracticeProgressRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  TunersDrumsRoute: typeof TunersDrumsRoute
  TunersGuitarRoute: typeof TunersGuitarRoute
  TunersUkuleleRoute: typeof TunersUkuleleRoute
  DrumsIndexRoute: typeof DrumsIndexRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
  SongsIndexRoute: typeof SongsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  PracticeDrumsLearnRoute: typeof PracticeDrumsLearnRoute
  PracticePianoLearnRoute: typeof PracticePianoLearnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-login': {
      id: '/agent-login'
      path: '/agent-login'
      fullPath: '/agent-login'
      preLoaderRoute: typeof AgentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chords': {
      id: '/chords'
      path: '/chords'
      fullPath: '/chords'
      preLoaderRoute: typeof ChordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grooves': {
      id: '/grooves'
      path: '/grooves'
      fullPath: '/grooves'
      preLoaderRoute: typeof GroovesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guitar': {
      id: '/guitar'
      path: '/guitar'
      fullPath: '/guitar'
      preLoaderRoute: typeof GuitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jam': {
      id: '/jam'
      path: '/jam'
      fullPath: '/jam'
      preLoaderRoute: typeof JamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano': {
      id: '/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof PianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings': {
      id: '/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof RecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukulele': {
      id: '/ukulele'
      path: '/ukulele'
      fullPath: '/ukulele'
      preLoaderRoute: typeof UkuleleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/songs': {
      id: '/admin/songs'
      path: '/admin/songs'
      fullPath: '/admin/songs'
      preLoaderRoute: typeof AdminSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/preferences': {
      id: '/api/preferences'
      path: '/api/preferences'
      fullPath: '/api/preferences'
      preLoaderRoute: typeof ApiPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drums/': {
      id: '/drums/'
      path: '/drums'
      fullPath: '/drums/'
      preLoaderRoute: typeof DrumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drums/tuner': {
      id: '/drums/tuner'
      path: '/drums/tuner'
      fullPath: '/drums/tuner'
      preLoaderRoute: typeof DrumsTunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/challenges': {
      id: '/practice/challenges'
      path: '/practice/challenges'
      fullPath: '/practice/challenges'
      preLoaderRoute: typeof PracticeChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/ear': {
      id: '/practice/ear'
      path: '/practice/ear'
      fullPath: '/practice/ear'
      preLoaderRoute: typeof PracticeEarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/progress': {
      id: '/practice/progress'
      path: '/practice/progress'
      fullPath: '/practice/progress'
      preLoaderRoute: typeof PracticeProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/': {
      id: '/songs/'
      path: '/songs'
      fullPath: '/songs/'
      preLoaderRoute: typeof SongsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/drums': {
      id: '/tuners/drums'
      path: '/tuners/drums'
      fullPath: '/tuners/drums'
      preLoaderRoute: typeof TunersDrumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/guitar': {
      id: '/tuners/guitar'
      path: '/tuners/guitar'
      fullPath: '/tuners/guitar'
      preLoaderRoute: typeof TunersGuitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tuners/ukulele': {
      id: '/tuners/ukulele'
      path: '/tuners/ukulele'
      fullPath: '/tuners/ukulele'
      preLoaderRoute: typeof TunersUkuleleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/drums/learn': {
      id: '/practice/drums/learn'
      path: '/practice/drums/learn'
      fullPath: '/practice/drums/learn'
      preLoaderRoute: typeof PracticeDrumsLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/piano/learn': {
      id: '/practice/piano/learn'
      path: '/practice/piano/learn'
      fullPath: '/practice/piano/learn'
      preLoaderRoute: typeof PracticePianoLearnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentLoginRoute: AgentLoginRoute,
  ChordsRoute: ChordsRoute,
  GroovesRoute: GroovesRoute,
  GuitarRoute: GuitarRoute,
  JamRoute: JamRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PianoRoute: PianoRoute,
  RecordingsRoute: RecordingsRoute,
  SignupRoute: SignupRoute,
  UkuleleRoute: UkuleleRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminSongsRoute: AdminSongsRoute,
  ApiPreferencesRoute: ApiPreferencesRoute,
  DrumsTunerRoute: DrumsTunerRoute,
  PracticeChallengesRoute: PracticeChallengesRoute,
  PracticeEarRoute: PracticeEarRoute,
  PracticeProgressRoute: PracticeProgressRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  TunersDrumsRoute: TunersDrumsRoute,
  TunersGuitarRoute: TunersGuitarRoute,
  TunersUkuleleRoute: TunersUkuleleRoute,
  DrumsIndexRoute: DrumsIndexRoute,
  PracticeIndexRoute: PracticeIndexRoute,
  SongsIndexRoute: SongsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  PracticeDrumsLearnRoute: PracticeDrumsLearnRoute,
  PracticePianoLearnRoute: PracticePianoLearnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
